# Generated by Django 2.1.2 on 2018-10-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonors',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
