# Generated by Django 2.1.2 on 2018-10-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0003_auto_20181018_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='eduDonationReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('currentedu', models.CharField(choices=[('none', 'none'), ('pri', 'Primary School'), ('hi', 'High School'), ('bach', "Bachelor's Degree"), ('mas', "Master's Degree")], max_length=50)),
                ('seekingedu', models.CharField(choices=[('none', 'none'), ('pri', 'Primary School'), ('hi', 'High School'), ('bach', "Bachelor's Degree"), ('mas', "Master's Degree")], max_length=50)),
                ('reqamt', models.DecimalField(decimal_places=0, max_digits=7)),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='eduDonors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('notification', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='blooddonors',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
