# Generated by Django 2.1.2 on 2018-10-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0004_auto_20181020_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edudonationreq',
            name='seekingedu',
            field=models.CharField(choices=[('pri', 'Primary School'), ('hi', 'High School'), ('bach', "Bachelor's Degree"), ('mas', "Master's Degree")], max_length=50),
        ),
    ]
