# Generated by Django 2.1.2 on 2018-10-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0006_edudonationreq_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edudonationreq',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
