# Generated by Django 2.1.2 on 2018-10-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0008_organdonors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organdonors',
            name='bloodgroup',
            field=models.CharField(choices=[('O+ve', 'O+ve'), ('O-ve', 'O-ve'), ('A+ve', 'A+ve'), ('A-ve', 'A-ve'), ('B+ve', 'B+ve'), ('B-ve', 'B-ve'), ('AB+ve', 'AB+ve'), ('AB-ve', 'AB-ve')], max_length=5),
        ),
    ]
