# Generated by Django 2.1.2 on 2018-10-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0010_auto_20181029_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organdonors',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organdonors',
            name='Religion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Buddhist', 'Buddhist'), ('Sikh', 'Sikh')], max_length=50),
        ),
    ]
