# Generated by Django 2.1.2 on 2018-11-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0013_fundraisers'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraisers',
            name='verification',
            field=models.BooleanField(default=0),
        ),
    ]
